import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1788891183215 implements MigrationInterface {
    name = 'InitialSchema1788891183215'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "application_documents" RENAME COLUMN "documentType" TO "document_type"`);
        await queryRunner.query(`ALTER TYPE "public"."application_documents_documenttype_enum" RENAME TO "application_documents_document_type_enum"`);
        await queryRunner.query(`ALTER TABLE "application_references" DROP COLUMN "contactName"`);
        await queryRunner.query(`ALTER TABLE "application_references" DROP COLUMN "officialEmail"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "pastAssignments"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "organisationName"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "organisationEmail"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "organisationPhone"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "cacRegistrationNumber"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "operatingState"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "experienceSummary"`);
        await queryRunner.query(`ALTER TABLE "application_references" ADD "fullName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_references" ADD "relationship" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_references" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "organisationLegalName" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."applications_registrationtype_enum" AS ENUM('REGISTERED_ENTITY', 'INSTITUTIONAL_UNIT', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "registrationType" "public"."applications_registrationtype_enum"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "yearEstablished" integer`);
        await queryRunner.query(`CREATE TYPE "public"."applications_organisationtype_enum" AS ENUM('INNOVATION_HUB', 'INCUBATOR', 'ACCELERATOR', 'TRAINING_PROVIDER', 'CREATIVE_HUBS', 'STARTUP_SUPPORT_ORGANIZATIONS', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "organisationType" "public"."applications_organisationtype_enum"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "websiteOrSocialHandle" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "primaryContactName" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "primaryContactRole" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "primaryContactPhone" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "primaryContactEmail" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."applications_statesofoperation_enum" AS ENUM('BENUE', 'KOGI', 'KWARA', 'NASARAWA', 'NIGER', 'JOS', 'PLATEAU', 'FCT')`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "statesOfOperation" "public"."applications_statesofoperation_enum" array`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "staffingSummary" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "taxClearanceCertificateUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "taxComplianceEvidenceUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "auditedAccountsUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "organogramUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "personnelCvUrls" jsonb`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "governanceStructure" text`);
        await queryRunner.query(`CREATE TYPE "public"."applications_sectorfocus_enum" AS ENUM('TECHNOLOGY', 'CREATIVE', 'HYBRID', 'ENTREPRENEURSHIP', 'RESEARCH_SUPPORT', 'INDUSTRY_LINKAGE')`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "sectorFocus" "public"."applications_sectorfocus_enum" array`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "programmeDeliveryTrackRecord" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "mentorshipIndustryNetwork" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "inclusionAccessibilityCapacity" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "existingInstitutionalRelationships" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "institutionalCoordinationPlan" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "staffFacultyEngagementPlan" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "beneficiaryReferralPlan" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "hasConductedIncubation" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "hasConductedAcceleration" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "monitoringReportingSystems" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "sustainabilityPlan" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "employmentPathway" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "safeguardingPolicyCommitted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "genderInclusionPolicyCommitted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "idiceReportingQaCommitted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "declarationOfAccuracyConfirmed" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "authorisedSignatoryTitle" character varying`);
        await queryRunner.query(`ALTER TABLE "application_references" ALTER COLUMN "organisationName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "physicalAddress"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "physicalAddress" text`);
        await queryRunner.query(`ALTER TYPE "public"."applications_proximitytohostinstitution_enum" RENAME TO "applications_proximitytohostinstitution_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."applications_proximitytohostinstitution_enum" AS ENUM('LESS_THAN_15_MINS', 'BETWEEN_15_30_MINS', 'OVER_30_MINS')`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "proximityToHostInstitution" TYPE "public"."applications_proximitytohostinstitution_enum" USING "proximityToHostInstitution"::"text"::"public"."applications_proximitytohostinstitution_enum"`);
        await queryRunner.query(`DROP TYPE "public"."applications_proximitytohostinstitution_enum_old"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "taxClearanceExpiry"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "taxClearanceExpiry" date`);
        await queryRunner.query(`ALTER TABLE "application_documents" DROP COLUMN "document_type"`);
        await queryRunner.query(`ALTER TABLE "application_documents" ADD "document_type" character varying NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "application_documents" DROP COLUMN "document_type"`);
        await queryRunner.query(`ALTER TABLE "application_documents" ADD "document_type" "public"."application_documents_document_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "taxClearanceExpiry"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "taxClearanceExpiry" TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."applications_proximitytohostinstitution_enum_old" AS ENUM('LESS_THAN_15_MINS', '15_30_MINS', 'OVER_30_MINS')`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "proximityToHostInstitution" TYPE "public"."applications_proximitytohostinstitution_enum_old" USING "proximityToHostInstitution"::"text"::"public"."applications_proximitytohostinstitution_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."applications_proximitytohostinstitution_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."applications_proximitytohostinstitution_enum_old" RENAME TO "applications_proximitytohostinstitution_enum"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "physicalAddress"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "physicalAddress" character varying`);
        await queryRunner.query(`ALTER TABLE "application_references" ALTER COLUMN "organisationName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "authorisedSignatoryTitle"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "declarationOfAccuracyConfirmed"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "idiceReportingQaCommitted"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "genderInclusionPolicyCommitted"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "safeguardingPolicyCommitted"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "employmentPathway"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "sustainabilityPlan"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "monitoringReportingSystems"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "hasConductedAcceleration"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "hasConductedIncubation"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "beneficiaryReferralPlan"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "staffFacultyEngagementPlan"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "institutionalCoordinationPlan"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "existingInstitutionalRelationships"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "inclusionAccessibilityCapacity"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "mentorshipIndustryNetwork"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "programmeDeliveryTrackRecord"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "sectorFocus"`);
        await queryRunner.query(`DROP TYPE "public"."applications_sectorfocus_enum"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "governanceStructure"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "personnelCvUrls"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "organogramUrl"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "auditedAccountsUrl"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "taxComplianceEvidenceUrl"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "taxClearanceCertificateUrl"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "staffingSummary"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "statesOfOperation"`);
        await queryRunner.query(`DROP TYPE "public"."applications_statesofoperation_enum"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "primaryContactEmail"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "primaryContactPhone"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "primaryContactRole"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "primaryContactName"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "websiteOrSocialHandle"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "organisationType"`);
        await queryRunner.query(`DROP TYPE "public"."applications_organisationtype_enum"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "yearEstablished"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "registrationType"`);
        await queryRunner.query(`DROP TYPE "public"."applications_registrationtype_enum"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "organisationLegalName"`);
        await queryRunner.query(`ALTER TABLE "application_references" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "application_references" DROP COLUMN "relationship"`);
        await queryRunner.query(`ALTER TABLE "application_references" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "experienceSummary" text`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "operatingState" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "cacRegistrationNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "organisationPhone" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "organisationEmail" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "organisationName" character varying`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "pastAssignments" jsonb`);
        await queryRunner.query(`ALTER TABLE "application_references" ADD "officialEmail" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_references" ADD "contactName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."application_documents_document_type_enum" RENAME TO "application_documents_documenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "application_documents" RENAME COLUMN "document_type" TO "documentType"`);
    }

}
