version: "3.3"

services:
  # api:
  #   build: .
  #   container_name: .
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env

  postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - eso_data:/var/lib/postgresql/data
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

networks:
  internal:

volumes:
  eso_data:
