name: CI/CD - NestJS

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build App
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [26]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: |
          docker build --target base -t $IMAGE_URI:$TAG_NAME .
          docker tag $IMAGE_URI:$TAG_NAME $IMAGE_URI:latest
        env:
          IMAGE_URI: ${{ secrets.DEV_REPO }}
          TAG_NAME: "v1"
          LATEST: "true"

      - name: Push Image
        run: |
          docker push $IMAGE_URI:$TAG_NAME
          docker push $IMAGE_URI:latest
        env:
          IMAGE_URI: ${{ secrets.DEV_REPO }}
          TAG_NAME: "v1"
          LATEST: "true"

      - name: Deploy To Server
        uses: fifsky/ssh-action@master
        with:
          command: |
            aws ecr get-login-password --region ${{  secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.DEV_REPO }}
            cd opensetting
            docker compose pull backend
            docker compose -f docker-compose.yml down backend
            docker compose -f docker-compose.yml up -d backend
            docker compose system prune
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
