
export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  IN_REVIEW_ELIGIBILITY = 'IN_REVIEW_ELIGIBILITY',
  REWORK_REQUIRED = 'REWORK_REQUIRED',
  IN_REVIEW_SCORING = 'IN_REVIEW_SCORING',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  SHORTLISTED = 'SHORTLISTED',
  PENDING_CONTEXTUAL_FEEDBACK = 'PENDING_CONTEXTUAL_FEEDBACK',
  PENDING_ECOSYSTEM_VALIDATION = 'PENDING_ECOSYSTEM_VALIDATION',
  VALIDATED_SHORTLISTED = 'VALIDATED_SHORTLISTED',
  MATCHED = 'MATCHED', 
  REJECTED = 'REJECTED',
}
