export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  IN_REVIEW_ELIGIBILITY = 'IN_REVIEW_ELIGIBILITY',
  REWORK_REQUIRED = 'REWORK_REQUIRED',
  IN_REVIEW_SCORING = 'IN_REVIEW_SCORING',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  SHORTLISTED = 'SHORTLISTED',
  PENDING_CONTEXTUAL_FEEDBACK = 'PENDING_CONTEXTUAL_FEEDBACK',
  PENDING_ECOSYSTEM_VALIDATION = 'PENDING_ECOSYSTEM_VALIDATION',
  VALIDATED_SHORTLISTED = 'VALIDATED_SHORTLISTED',
  MATCHED = 'MATCHED',
  REJECTED = 'REJECTED',
}

export enum RegistrationType {
  REGISTERED_ENTITY = 'REGISTERED_ENTITY',
  // NGO_CSO = 'NGO_CSO',
  // COOPERATIVE = 'COOPERATIVE',
  // UNIVERSITY_AFFILIATED = 'UNIVERSITY_AFFILIATED',
  INSTITUTIONAL_UNIT = 'INSTITUTIONAL_UNIT',
  OTHER = 'OTHER',
}

export enum OrganisationType {
  INNOVATION_HUB = 'INNOVATION_HUB',
  INCUBATOR = 'INCUBATOR',
  ACCELERATOR = 'ACCELERATOR',
  TRAINING_PROVIDER = 'TRAINING_PROVIDER',
  CREATIVE_HUBS = 'CREATIVE_HUBS',
  STARTUP_SUPPORT_ORGANIZATIONS = 'STARTUP_SUPPORT_ORGANIZATIONS',
  OTHER = 'OTHER',
}

export enum SectorFocus {
  TECHNOLOGY = 'TECHNOLOGY',
  CREATIVE = 'CREATIVE',
  HYBRID = 'HYBRID',
  ENTREPRENEURSHIP = 'ENTREPRENEURSHIP',
  RESEARCH_SUPPORT = 'RESEARCH_SUPPORT',
  INDUSTRY_LINKAGE = 'INDUSTRY_LINKAGE',
}

export enum OperatingState {
  BENUE = 'BENUE',
  KOGI = 'KOGI',
  KWARA = 'KWARA',
  NASARAWA = 'NASARAWA',
  NIGER = 'NIGER',
  JOS = 'JOS',
  PLATEAU = 'PLATEAU',
  FCT = 'FCT',
}

export enum ProximityToHost {
  LESS_THAN_15_MINS = 'LESS_THAN_15_MINS',
  BETWEEN_15_30_MINS = 'BETWEEN_15_30_MINS',
  OVER_30_MINS = 'OVER_30_MINS',
}

export interface TransitionContext {
  targetStatus: ApplicationStatus;
  actorId?: string;
  role?: string;
  metadata?: Record<string, any>;
}