export enum EmploymentOutcomeType {
  FORMAL_EMPLOYMENT = 'FORMAL_EMPLOYMENT',
  FREELANCE = 'FREELANCE',
  REMOTE_WORK = 'REMOTE_WORK',
  SELF_EMPLOYMENT = 'SELF_EMPLOYMENT',
  ENTERPRISE_LAUNCH = 'ENTERPRISE_LAUNCH',
}
