export enum Role {
  ESO = 'ROLE_ESO',
  ELIGIBILITY_REVIEWER = 'ROLE_ELIGIBILITY_REVIEWER',
  SCORING_REVIEWER = 'ROLE_SCORING_REVIEWER',
  VALIDATOR = 'ROLE_VALIDATOR',
  SYSADMIN = 'ROLE_SYSADMIN',
}
